### ISSUE TITLE
Fish causing lag

### ISSUE THREAD

**Issue by E-daw** [CreativeMD/AmbientSounds#168]
I'm having a really weird issue, currently all fish in the game, including ones added by aquaculture seem to be causing a lot of lag. Whenver I mute the ingame sound, the lag spikes go away completely.  Removing ambient sounds fixes the issue, so does turning off audio.

I'm on the latest 1.19.2 version v5.2.13 and I'm on creative core v2.9.3.

**Comment by CreativeMD** [comment]
First of all for responding that late to your issue. This does not seem to be related to AmbientSounds to be honest, but maybe you do not have enough RAM? You can use F3 to see how much RAM is available and used. Maybe you can check that.

**Comment by Bronski** [comment]
FYI: I also had this happening last week on 1.20. Trying to reel in a fish often/usually resulted in no catch. I tried waiting a little longer to click but that didn't seem to help much.

It didn't start until I added just this mod. It went away when I removed it again. I also had Aquaculture 2 so maybe that's a clue but I don't know.

**Comment by CreativeMD** [comment]
I tested it on 1.20 and fishing works absolutely fine no issue, even with Aquaculture 2 installed.

**Comment by Bronski** [comment]
It's happening on 1.20.1 as well for me (Luna Pixels Prominence II Forge this time, but that wasn't my base last time). I can get you the full mod list if you want to chase it.

It was raining when I noticed it again, but that may not be an absolute rule.

I removed this mod again and it went away. 🤷‍♂️

**Comment by CreativeMD** [comment]
It can take minutes ... I don't think AmbientSounds does change anything about that.

**Comment by Bronski** [comment]
If you mean minutes to get a bite, that's not what I mean. I mean when the bobber jumps and the sound plays. Normally, you can right click very quickly and get a cast, or wait just a moment and still get one. When this is occurring, frequently nothing happens when you right-click, not instantly and not even if you wait a bit. It's as if your timing was way off. That's probably why the OP called it "lag."

Maybe someone else will chime in with more useful info to help track it down. 🤷‍♂️

**Comment by CreativeMD** [comment]
But then it is a fps problem? Maybe there is not enough RAM or maybe it just lags from time to time. You could use F3 + ALT to see the performance graph maybe you notice something there?
