### ISSUE TITLE
settings keep resetting

### ISSUE THREAD

**Issue by Nitero** [CreativeMD/AmbientSounds#169]
on 1.19.2 when you make a change like adjusting the volume of a biome, then save and restart minecraft, the fade-volume and fade-pitch get set to 0, resulting in no audio at all

if you know this then isn't not a big issue to set it back to 0.005 but if you're unaware then it can take some time to find the issue

**Comment by CreativeMD** [comment]
This is a known issue fixed in the newest version of CreativeCore, but only for 1.19.4. This issue will occur every time you open the settings from ambientsounds. I recommend to reset the value and then processed to change all settings related to ambientsounds via the config file. Sorry for all the trouble. This issue has been around for quite a while know until recently somebody helped me to figure out what is causing it. That's why it's only available for 1.19.4.
