### ISSUE TITLE
[Feature Request] optional integration with Sound Physics Remastered

### ISSUE THREAD

**Issue by Magicrafter13** [CreativeMD/AmbientSounds#183]
I love the sounds of this mod, but I do notice that they don't change when I move my head - so I assume all sounds are being played at the player's location - which also likely explains why I never hear any of them muffled or with any other of the features of Sound Physics Remastered.

Picking random locations in the biome to play the sounds in would have an effect even in vanilla, and would likely make this mod work well with Sound Physics Remastered without actually writing any code specifically to interface with that mod.

**Comment by CreativeMD** [comment]
It's actually not that easy to do. There are lot of information to collect. There plenty of sounds and different scenarios. The system would need to find a position for all the combination of conditions. My fear is that this will take a lot of time to implement and affect performance too much. I will add it to my todo list. Maybe at some point in the future I will do something like this, but not for now. Sorry for the late response. I will close this issue here, but feel free to respond here anyway.
