### ISSUE TITLE
Deep dark ambient sound triggering near player placed skulk blocks

### ISSUE THREAD

**Issue by Padex98** [CreativeMD/AmbientSounds#184]
Pretty self explanatory! I places some skulk blocks in my base for decoration, but now whenever I enter the room I get the deep dark ambient noises

**Comment by CreativeMD** [comment]
Can you use the command /ambient-debug. Stand next to it, make a screenshot and post it here? Will make it a lot easier to figure out why the sound is playing.

**Comment by Padex98** [comment]
Gof showing when the soundscape gets triggered: https://imgur.com/wsAW2cF
![image](https://github.com/CreativeMD/AmbientSounds/assets/83363845/b497260d-aee6-4aed-b4d8-dc485e2ee566)

I made a gif to maybe showcase it better

**Comment by Padex98** [comment]
As you can see, the moment I get in the room, since I have skulk blocks on the ceiling, the deep dark ambience triggers

**Comment by CreativeMD** [comment]
Hey sorry for not responding earlier. I thought about how this situation could be solved, but I actually I do not see a good solution from my end. They are just too many blocks of the deep dark. If I change anything here it will effect the deep dark too much. You could add a layer of glass or other transparent blocks in between to block the detection from ambientsounds. This this sound like a proper solution? Otherwise you could think about disabling the deep dark volume entirely using /cmdclientconfig.

Possible solution -> why I don't like it:
* make deep dark sounds also require stone to be around (to ensure it is a cave) -> often not the case in deep dark biomes (will cause issue).
* make it depend on light -> this would make sound fade away as soon as you light up the deep dark.
* make it depend on the height -> would work in normal circumstances, but I'm not a fan of this, because I want AmbientSounds to be adaptive to as many as scenarios as possible. So I do not like this solution, because it will not work for causes where you "build" a deep dark above the surface level.

**Comment by CreativeMD** [comment]
I will close this issue for now. Feel free to post suggestions or your ideas here.
