### ISSUE TITLE
Suspected crash of client when come into unloaded chunk from loaded

### ISSUE THREAD

**Issue by vgrynch** [CreativeMD/AmbientSounds#186]
AmbientSounds_FORGE_v5.2.13_mc1.19.2, client is 1.19.2 Forge v. 43.2.14
[23Jul2023 19:40:24.332] [Sound engine/ERROR] [com.mojang.blaze3d.audio.OpenAlUtil/]: Allocate new source: Invalid parameter parameter value.

(The last log entry for MC client. No other errors or exception stack traces).

I suspect this *might* be related to this mod as the crash happened immediately as I entered unloaded from the server chunk while flying in creative mode low above the forest. Forest nature sounds were on, and Minecraft ambient music was on right before that.

**Comment by CreativeMD** [comment]
I don't think this crash is related to AmbientSounds. If there is no crash-report there has to be a hs_err_pid<number>.log Maybe you can upload the newest one here?

**Comment by vgrynch** [comment]
Here it is
[hs_err_pid14880.log](https://github.com/CreativeMD/AmbientSounds/files/12148916/hs_err_pid14880.log)

**Comment by vgrynch** [comment]
It happened a second time, BTW. Did not try anymore. If continue, I will start removing mods to see what actually causes it, if not this one. Let me know if the above info helps.

**Comment by CreativeMD** [comment]
The reports shows a crash which happened when loading textures to the graphics card. Maybe update your graphic card driver?
Not 100% sure but it also appears that your CPU is used to render things. This can happen if you plug in your monitor into the display adapter of the motherboard instead of directly into the graphic card slots. You can also check that if you launch minecraft hit F3. There is some information displayed which tells you what graphic chip is used.

You can also ask Mojang about this issue.
