### ISSUE TITLE
Spatial audio support?

### ISSUE THREAD

**Issue by ThemovieaYT** [CreativeMD/AmbientSounds#205]
Hello! I am Themoviea and was playing All of Fabric 7 with your mod on it. I like your ambient sounds as it makes the game more alive. However, I noticed that the ambient sounds seem like it's only using stereo. Minecraft officially supports 3D spacial audio using the HRTF directional audio feature. I thought it would be cool to add that support to the mod somehow because it would feel even more fantastic hearing it in headphones. Cheers!

![image](https://github.com/CreativeMD/AmbientSounds/assets/66336915/157a5446-c3ef-44f3-9ef9-4c6d91474d15)

**Comment by CreativeMD** [comment]
Unfortunately this is not possible. AmbientSounds analysis the environment and plays sounds that fit. They are not bound to any location. That's why I cannot use directional sound. I thought about fixing it by playing these sounds at random locations but this is quite an ambiguous task. I feel like it is not worth the time investment. It will also impact performance in a bad way. It would need a lot more calculations to make this work properly. Maybe at some point in the future I do it (if I have a good idea), but for now it will stay as it is.
