### ISSUE TITLE
All sounds except for the mods ones are turned off after playing for 5 minutes

### ISSUE THREAD

**Issue by Morgan51445** [CreativeMD/AmbientSounds#212]
After playing for a short while, all other sounds that are not a part of the mod will turn off. No subtitles appear either.
The sound turns back on if I mute and then unmute the master sound setting. 

This is very irritating and I cannot find a fix anywhere.

I believe it turns off other sounds if too many occur at the same time, but I am unsure.

This happens consistently, over the past 2 days since installing.

**Comment by CreativeMD** [comment]
There are an issue with the config. Go to /cmdclientconfig -> AmbientSounds and reset the values for fadeVolume and fadePitch. Maybe you are also using an outdated version of CreativeCore? Would also be good to know what minecraft version you are using. You can also use the command /ambient-debug to see which sounds are currently playing. Maybe that helps to pin point the issue further if my first suggestion does not fix it.

Also I'm very sorry for responding sooo late ... I'm have been quite busy.

**Comment by NekoCarvi** [comment]
I have the same problem but it only happens in the nether fortress. The suspense sound is played until the sound reaches the 245/245 limit on the debug screen.

Minecraft: 1.19.2 Forge: 43.3.7
AmbientSounds: 5.2.13 CreativeCore: 2.9.4

![2024-03-06_16 45 37](https://github.com/CreativeMD/AmbientSounds/assets/157254184/f352bc9d-61e5-4522-9ad8-154dc171e2d9)
![2024-03-06_16 45 58](https://github.com/CreativeMD/AmbientSounds/assets/157254184/cf0b3bb5-60ce-44fb-8384-45c82fb51762)

I also noticed that the number seen in the suspense sound does not stop increasing at any time, I don't know if this is relevant but other sounds in the ambient debug screen the number shown does not have any change

![2024-03-06_16 46 19](https://github.com/CreativeMD/AmbientSounds/assets/157254184/1cb8218f-ccb0-41ee-ac99-635b84b1692e)

And if I use the combination F3 + T the sounds on the debug screen return to 0/245 but again it does not stop rising until it reaches the limit again, 245/245, approximately it takes a minute to reach the limit again.

Once it reaches the limit all vanilla sounds are silenced but mod sounds such as bird songs or similar can still be heard.

![2024-03-06_16 47 32](https://github.com/CreativeMD/AmbientSounds/assets/157254184/234395b6-15cf-4064-bbad-703b91a87a3f)
![2024-03-06_16 47 46](https://github.com/CreativeMD/AmbientSounds/assets/157254184/349b9a79-9383-4050-a313-11de258ada92)

When I return to the overworld the sound limit remains at 245/245 and I have to use F3 + T to reload the sounds but since I am not in the nether now the sounds remain between 3/245 - 15/245 but They do not exceed that limit. So this error occurs in the nether and only in the fortress from what I can see.

Is there a way to avoid this error with that suspense sound effect?

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. If this issue persists just report it back here.
