### ISSUE TITLE
if sculk is in the surface then deep dark ambience will play [Fabric 1.20.1]

### ISSUE THREAD

**Issue by memphismc** [CreativeMD/AmbientSounds#216]
https://github.com/CreativeMD/AmbientSounds/assets/129392333/501af126-ec0c-4330-8b79-da082629abf4

pretty sure this isnt intended as underground sounds can be heard in the surface with this

**Comment by CreativeMD** [comment]
Is that a bug? I mean after all the deep dark stuff is pretty creepy and should only be found underground. Problem is that it is not that easy to fix it. I could only make it play when it is inside a cave, but sometimes these deep dark biomes are too large so that the normal cave is not considered to be there. Hard to explain, but currently I do not see a got way to get around it. I could also check for light source ... but in that case the sounds in deep dark would disappear as soon as there is enough light which would be bad as well.

**Comment by memphismc** [comment]
i dont know, this is the same with moss blocks

if you place moss blocks, frogs start croaking making the mod think that just because theres moss blocks its a lush cave (atleast i think thats what the biome is, also i havent tried this in the surface, would you like me to try it?)

**Comment by memphismc** [comment]
oh and for context: the way i found this is through a modded enchantment called catalysis which spawns all that sculk when defeating a mob, i happened to step on that sculk and the ambience played despite me being on the surface

so all in all its more of a mod compatibility thing than anything i guess, ive already disabled the catalysis enchahtment since it has no real use gsmeplay-wise

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. In the newest version of AmbientSounds the lush and deep dark sounds only play if you considered to be in a cave, which means you are at least blocks under the average height of the blocks around you. So I guess this can only happen if you are in the basement?

If the issue still persists would it be possible to create a test world so I can see if I can tweak the settings a bit?

**Comment by CreativeMD** [comment]
Will close this issue due to inactivity. Feel free to respond here again.
