### ISSUE TITLE
[Suggestion] Wind strength variation

### ISSUE THREAD

**Issue by Macintosh-Fan** [CreativeMD/AmbientSounds#220]
The feature request is the ability to have the wind strength vary depending on the time of day for some biomes, kinda like how the wind is stronger in the afternoon on warmer days in some areas, but always kinda windy on top of mountains.

**Comment by CreativeMD** [comment]
I don't think this is the goal of AmbientSounds. Wind strength should depend on the weather. I know at least one mod which does these calculations, but AmbientSounds cannot do it, because it's on client side only. However I have added more wind variants, which play at random times. Maybe that helps out a bit.
