### ISSUE TITLE
Compatibility/Support for Climatic Biomes Placement Mod.

### ISSUE THREAD

**Issue by Thombias** [CreativeMD/AmbientSounds#31]
Here's a list of what biomes in the Climatic Biomes Placement Mod need a fix in my opinion:

-**Subtropical Forest** (climaticbiomesjbg:subtropical_forest)
-**Subtropical Forest Hills** (climaticbiomesjbg:subtropical_forest_hills)
These Biomes currently use sound effects from Jungles. However they look way more similar to default forests rather than jungles. They have oak and pine trees (added by the mod) and a slightly more greenish grass than default forests. But the jungle sounds really don't fit, Forest sounds would sound a lot better and more fitting for them.

-**Dry Scrub** (climaticbiomesjbg:dry_scrub)
-**Dry Scrub Hills** (climaticbiomesjbg:dry_scrub_hills)
They only use the Savanna biome sounds but they are actually a mix of both Savanna and Desert. Grass, scrubs and large patches of sand generate here, so with both the Desert sounds and Savanna sounds playing simultaneously it would fit their theme more, especially since both sound effects are pretty quiet.

-**Tropical Extreme Hills** (climaticbiomesjbg:hot_mountain)
-**Tropical Forested Extreme Hills** (climaticbiomesjbg:hot_mountain_trees)
Both of these use the Extreme Hills and Jungle sounds simultaneously. The Tropical Extreme Hills should only use the default Extreme Hills biome sounds since they barely have trees. As for the Tropical Forested variant i would say they're fine with both the Extreme Hills and Jungle biome sound effects.

And here's a list of biomes that already have fitting sound effects, just in case you want to know what else biomes this mod offers:

-**Tropical Forest** (climaticbiomesjbg:tropical_forest)
-**Tropical Forest Hills** (climaticbiomesjbg:tropical_forest_hills)
-**Pine Woods** (climaticbiomesjbg:pine_swamp)
-**Dense Scrub** (climaticbiomesjbg:dense_scrub)
-**Dense Scrub Hills** (climaticbiomesjbg:dense_scrub_hills)
These are the biomes that already have fitting sound effects thanks to the auto-detection.

I hope i made this post clear enough for you to understand. if there's anything missing or wrong, please let me know!

**Comment by CreativeMD** [comment]
Thanks for your detailed information. Unfortunately I could not implement them for a long time because I have been working on a rework of AmbientSounds, which is about to be finished now.

It's not really tested, so I would be very happy if you could provide some feedback, your suggestions should be included. You can use /ambient-debug to see detailed information about which sound is playing at the moment (might come in handy to trace down issue).

https://www.dropbox.com/s/seoavzwuqfhh413/AmbientSounds_v3.0.0.jar?dl=1

Furthermore I sent the new version to another issue (https://github.com/CreativeMD/AmbientSounds/issues/30). I would be happy if you could post your feedback (if you have some) there. I would like to use this issue for you specified requests (so you can post information these here). Hope I didn't confuse you.

**Comment by CreativeMD** [comment]
AmbientSounds v3.0.0 has been released!
