### ISSUE TITLE
Plains sounds in non-grass areas

### ISSUE THREAD

**Issue by 1eo1i** [CreativeMD/AmbientSounds#97]
Hi, I have a few questions regarding the detection of grass as a top block:

Even though there is no grass around, there are still loud 'plains' sounds, such as the crickets. 
![2021-10-27_14 09 12](https://user-images.githubusercontent.com/61970761/138987546-1dc03615-21dd-4bcd-9c79-887fc19486ae.png)

In addition, while 'plains' sounds play in grass areas, 'grass' sounds do not. For instance, if I only turn off 'plains.cricket' in the config, there is absolute silence, even in grassy areas - I cannot get 'grass.cricket' to play. Also, grass areas in non-plains biomes, such as mountain biomes, don't have cricket sounds.
![2021-10-27_14 11 53](https://user-images.githubusercontent.com/61970761/138987553-41a36b86-69c9-43f3-8370-e4c4e20a8cc3.png)

I have tested this in MC 1.16.5 mod version 3.1.10, and 1.17.1 mod version 4.0.3. 
Sorry for bothering you, thanks for your help!

**Comment by CreativeMD** [comment]
Hey, AmbientSounds does not scan the environment like some other mods do. If you are in a plains biome near the surface you will here plains sounds no matter if it's made out of rock for some reason. Same goes for highland, it's supposed to be cold that's why there are no cricket noises, but heavy wind because it's "highland" and it works quite well in a normal minecraft world.

Scanning the environment is quite costly in terms of performance. Sorry to disappoint you in that regard. Maybe there will be some changes to the system in the future, but for now I will stick to it.

**Comment by 1eo1i** [comment]
Oh I see. Thanks for the clarification!
